# -*- coding: utf-8 -*-
"""gnyq

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sInBF7F1OBLc5q40ZUzji4HR1i3Ygigy
"""

import numpy as np
from matplotlib import pyplot as plt
from scipy import pi
from scipy.fft import fft,fftshift

# sampling rate  
samp_rate = 1000
time = np.linspace(-1,1,2*samp_rate)
output = np.sinc(700*time)+np.sinc(500*time)
# sampling rate = 1/(length of input sequence)
freq = np.linspace(-500,500,2000)
freq_data = fft(output)
four = np.abs(freq_data)
plt.subplot(1,2,1)
plt.plot(freq,fftshift(four))
plt.xlabel("Frequency")
plt.ylabel("Amplitude")
plt.grid()
plt.title('Sampling rate = 1k')

# Nyquist rate = 700
# sampling rate  
samp_rate = 2000
time = np.linspace(-1,1,2*samp_rate)
output = np.sinc(700*time)+np.sinc(500*time)
# sampling rate = 1/(length of input sequence)
freq = np.linspace(-1000,1000,4000)
freq_data = fft(output)
four = np.abs(freq_data)
plt.subplot(1,2,2)
plt.plot(freq,fftshift(four))
plt.xlabel("Frequency")
#plt.ylabel("Amplitude")
plt.xlim(-500,500)
plt.grid()
plt.title("Sampling rate = 2k")

plt.suptitle("Sampling rate > Nyquist rate")
plt.show()