# -*- coding: utf-8 -*-
"""EE3900_As5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/135Q-mVc_zmDXVPJZrsPooKcVnHCSC1OK
"""

import numpy as np
from matplotlib import pyplot as plt
from matplotlib.patches import Ellipse

plt.figure()
ax = plt.gca()
# plot of ellipse with origin as center and a=5,b=3,e=4/5
ellipse = Ellipse(xy=(0,0),width=10,height=6,edgecolor='r',fc='None',lw=2,label='ellipse')
ax.add_patch(ellipse)
# plot of line x=ae=4
line = plt.Line2D((4,4),(-4,4),color='g',lw=2,label='x=ae')
ax.add_line(line)
plt.axis('scaled')
plt.axhline(color='black',lw=1)
# plot of points
X = np.array([4,5,4,4])
Y = np.array([0,0,9/5,-9/5])
plt.scatter(X,Y,color='black')
plt.text(X[0]*(0.9),Y[0]+(0.24),'D')
plt.text(X[1]*(1.04),Y[1]+(0.14),'B')
plt.text(X[2]*(0.9),Y[2]*(1.24),'A')
plt.text(X[3]*(0.9),Y[3]*(1.34),'C')
#plt.axvline()
plt.grid()
plt.legend()
plt.show()